/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html","./src/**/*.{vue,js,ts,jsx,tsx}"],
  safelist: [
    'bg-purple-400',
    'bg-orange-400',
    'bg-blue-400',
    'bg-blue-500',    
    'bg-green-400',
    'bg-yellow-400',
    'bg-info',
    'bg-success',
    'bg-warning',
    'bg-error',
    'badge-info',
    'badge-success',    
    'badge-warning',
    'badge-error',
    'radio-info',
    'radio-success',
    'radio-warning',
    'radio-error',
    'tooltip-info',
    'tooltip-success',
    'tooltip-warning',
    'tooltip-error',
    'alert-info',
    'alert-success',
    'alert-warning',
    'alert-error'

  ],  
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ],
  },  
  /*theme: {
    extend: {
      colors: {
        primary: '#86A6DB',
        secondary: '#7A838F',
        header1: '#9EA7FC',
        header2: '#65B6F7',
        logo: '#32325D',
        main: '#EEF2F9',
        board: '#E9EBF0',
      },

    },
  },*/
  screens: {
    'sm': { min: '320px', max: '480px' },
    'md': { min: '481px', max: '768px' },
    'lg': { min: '769px', max: '1024px' },
    'xl': { min: '1025px', max: '1200px' },
    '2xl': { min: '1201px' },
  },
  plugins: [
    require('tailwind-scrollbar')({ nocompatible: true }),
    require("daisyui"),
  ],
}

